mt5:
  server: MetaQuotes-Demo
  login: null
  password: null
  timeout: 60000
  simulation: true

trading:
  symbol: BTCUSD
  timeframe: M5
  risk_per_trade: 0.01
  enable_auto_trading: false
  max_open_positions: 3

indicators:
  rsi:
    length: 14
    overbought: 70
    oversold: 30
  macd:
    fast: 12
    slow: 26
    signal: 9

openai:
  model: gpt-4o  # the newest OpenAI model is "gpt-4o" which was released May 13, 2024
  temperature: 0.2

scheduler:
  analysis_interval: 5  # minutes
  reflection_interval: 60  # minutes

stream:
  update_interval: 1.0
  symbols: 
    - BTCUSD
  enable_websocket: true
  websocket_port: 8765
