indicators:
  macd:
    fast: 12
    signal: 9
    slow: 26
  rsi:
    length: 14
    overbought: 70
    oversold: 30
mt5:
  login: '239185318'
  password: Dev@2025
  server: Exness-MT5Trial6
  simulation: true
  timeout: 60000
openai:
  model: gpt-4o
  temperature: 0.2
scheduler:
  analysis_interval: 5
  reflection_interval: 60
stream:
  enable_websocket: true
  symbols:
  - BTCUSD
  update_interval: 1.0
  websocket_port: 5678
trading:
  enable_auto_trading: false
  max_open_positions: 3
  risk_per_trade: 0.01
  symbol: BTCUSD
  timeframe: M5
